site_name: BRF Portal

repo_url: https://github.com/brfportal/docs.git
site_description: 'BRF Portal – Administrera din förening'
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Getting Started: 'index.md'
  - Startsida:
    - 'Översikt': 'dash/main.md'